### ISSUE TITLE
Fails running with yarn 2

### ISSUE THREAD

**Issue by barbogast** [nrwl/add-nx#28]
Hi :-)

I just tried to run `yarn dlx add-nx-to-monorepo` and got the following error:

```
Error: add-nx-to-monorepo tried to access tslib, but it isn't declared in its dependencies; 
this makes the require call ambiguous and unsound.
```

I'm using yarn v3.0.2

Full output:
```
/private/var/folders/4y/blwdwqdx3j19xg3crjw608s80000gp/T/xfs-998e284c/dlx-5866/.pnp.cjs:11760
    throw firstError;
    ^

Error: add-nx-to-monorepo tried to access tslib, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: tslib
Required by: add-nx-to-monorepo@npm:1.4.1 (via /Users/ben1/.yarn/berry/cache/add-nx-to-monorepo-npm-1.4.1-9a8f29eea3-8.zip/node_modules/add-nx-to-monorepo/src/)

Require stack:
- /Users/ben1/.yarn/berry/cache/add-nx-to-monorepo-npm-1.4.1-9a8f29eea3-8.zip/node_modules/add-nx-to-monorepo/src/add-nx-to-monorepo.js
    at Function.external_module_.Module._resolveFilename (/private/var/folders/4y/blwdwqdx3j19xg3crjw608s80000gp/T/xfs-998e284c/dlx-5866/.pnp.cjs:11759:55)
    at Function.external_module_.Module._load (/private/var/folders/4y/blwdwqdx3j19xg3crjw608s80000gp/T/xfs-998e284c/dlx-5866/.pnp.cjs:11558:48)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/ben1/.yarn/berry/cache/add-nx-to-monorepo-npm-1.4.1-9a8f29eea3-8.zip/node_modules/add-nx-to-monorepo/src/add-nx-to-monorepo.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.external_module_.Module._load (/private/var/folders/4y/blwdwqdx3j19xg3crjw608s80000gp/T/xfs-998e284c/dlx-5866/.pnp.cjs:11608:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
```

**Comment by BasixKOR** [comment]
It is because the `importHelpers` flag is enabled. It instructs TSC to import `tslib` for common operations. I think this issue can be solved by just adding `tslib` to the dependencies. Would you mind if I open a pull request to resolve this?

**Comment by mandarini** [comment]
Hi @BasixKOR ! Yes please, open a PR, and I'll ping the right ppl :P

**Comment by nagad814** [comment]
please fix this
